[colors]
[colors.primary]
background = "#f9fdff"
foreground = "#424258"

[colors.normal]
black   = "#f9fdff"
red     = "#cd4034"
green   = "#51a45d"
yellow  = "#e7b45d"
blue    = "#0a537c"
magenta = "#9c85a7"
cyan    = "#30a1a9"
white   = "#424258"

[colors.bright]
black   = "#6c6c65"
red     = "#a51d2d"
green   = "#007a00"
yellow  = "#b68618"
blue    = "#00b3f4"
magenta = "#9e2475"
cyan    = "#0094c3"
white   = "#1c222a"

[colors.cursor]
text   = "#f9fdff"
cursor = "#424258"
