[colors]
[colors.primary]
background = "#f9fdff"
foreground = "#424258"

[colors.normal]
black   = "#f9fdff"
red     = "#ea0000"
green   = "#2d6c53"
yellow  = "#987c46"
blue    = "#0a537c"
magenta = "#9870ac"
cyan    = "#446881"
white   = "#424258"

[colors.bright]
black   = "#6c6c65"
red     = "#ea0000"
green   = "#2d6c53"
yellow  = "#987c46"
blue    = "#56b0df"
magenta = "#9870ac"
cyan    = "#446881"
white   = "#1c222a"

[colors.cursor]
text   = "#f9fdff"
cursor = "#424258"
