mode = "light"

# UI Colors (extended)
accent = "#0a537c"
cursor = "#424258"

# Primary colors
foreground = "#424258"
background = "#f9fdff"

# Normal colors (ANSI 0-7)
color0 = "#f9fdff"
color1 = "#ea0000"
color2 = "#2d6c53"
color3 = "#987c46"
color4 = "#0a537c"
color5 = "#9870ac"
color6 = "#446881"
color7 = "#424258"

# Bright colors (ANSI 8-15)
color8 = "#6c6c65"
color9 = "#ea0000"
color10 = "#2d6c53"
color11 = "#987c46"
color12 = "#56b0df"
color13 = "#9870ac"
color14 = "#446881"
color15 = "#1c222a"
