# Background and foreground colors
background = #f9fdff
foreground = #424258

# Standard colors
palette = 0=#f9fdff
palette = 1=#424258
palette = 2=#939384
palette = 3=#9f8256
palette = 4=#0a537c
palette = 5=#414766
palette = 6=#0a7091
palette = 7=#424258

# Bright colors
palette = 8=#6c6c65
palette = 9=#de0000
palette = 10=#007a00
palette = 11=#958a55
palette = 12=#00b3f4
palette = 13=#ff345a
palette = 14=#7ce1e9
palette = 15=#1c222a
