$color = rgba(249, 253, 255, 1)
$inner_color = rgba(249, 253, 255, 0.66)
$outer_color = rgba(65, 71, 102, 1)
$font_color = rgba(66, 66, 88, 1)
$placeholder_color = rgba(66, 66, 88, 0.7)
$check_color = rgba(10, 112, 145, 1)
