# This file is not a full hyprland configuration.
# It is intended to be included in your main hyprland.conf.

$activeBorderColor = rgb(000900)

general {
    border_size = 1
    col.active_border = $activeBorderColor
    col.inactive_border = rgb(BBC2B8)
}

group {
    col.border_active = $activeBorderColor
}

decoration {
    rounding = 5
    rounding_power = 2

    inactive_opacity = 0.68
    fullscreen_opacity = 1.0

    shadow {
        enabled = true
        range = 8
        render_power = 4
        color = rgba(90A5A755)
        color_inactive = rgba(4C626415)
    }

    blur {
        enabled = false
		ignore_opacity = false
		size = 2
		brightness = 0.8
    }
}

windowrule = opacity 1.0 override 1.0 override, match:class ^(imv|mpv|vlc|org.gnome.NautilusPreviewer|org.gnome.Evince|com.gabm.satty|zoom|org.kde.kdenlive|com.obsproject.Studio|com.github.PintaProject.Pinta)$
windowrule = opacity 1.0 override 1.0 override, match:class ^(gimp|com.github.xournalpp.xournalpp|nwg-look|system-config-printer)$
windowrule = opacity 0.75, match:class ^(Alacritty|kitty|com.mitchellh.ghostty)$
